// Generated by scripts/build-foundation.mjs. Do not edit by hand.
export const foundationTokens = {
  "accessibility": {
    "focusRingWidth": {
      "$type": "dimension",
      "$value": "2px"
    },
    "focusRingOffset": {
      "$type": "dimension",
      "$value": "2px"
    },
    "minimumTarget": {
      "$type": "dimension",
      "$value": "44px"
    },
    "contrastBodyText": {
      "$type": "number",
      "$value": 4.5
    },
    "contrastLargeText": {
      "$type": "number",
      "$value": 3
    }
  },
  "breakpoint": {
    "sm": {
      "$type": "dimension",
      "$value": "640px"
    },
    "md": {
      "$type": "dimension",
      "$value": "768px"
    },
    "lg": {
      "$type": "dimension",
      "$value": "1024px"
    },
    "xl": {
      "$type": "dimension",
      "$value": "1280px"
    },
    "2xl": {
      "$type": "dimension",
      "$value": "1536px"
    }
  },
  "motion": {
    "duration": {
      "instant": {
        "$type": "duration",
        "$value": "0ms"
      },
      "fast": {
        "$type": "duration",
        "$value": "150ms"
      },
      "base": {
        "$type": "duration",
        "$value": "240ms"
      },
      "slow": {
        "$type": "duration",
        "$value": "420ms"
      }
    },
    "easing": {
      "standard": {
        "$type": "cubicBezier",
        "$value": [
          0.2,
          0,
          0,
          1
        ]
      },
      "emphasized": {
        "$type": "cubicBezier",
        "$value": [
          0.2,
          0,
          0,
          1.2
        ]
      }
    }
  },
  "radius": {
    "none": {
      "$type": "dimension",
      "$value": "0px"
    },
    "xs": {
      "$type": "dimension",
      "$value": "4px"
    },
    "sm": {
      "$type": "dimension",
      "$value": "6px"
    },
    "md": {
      "$type": "dimension",
      "$value": "8px"
    },
    "lg": {
      "$type": "dimension",
      "$value": "12px"
    },
    "xl": {
      "$type": "dimension",
      "$value": "16px"
    },
    "pill": {
      "$type": "dimension",
      "$value": "999px"
    }
  },
  "spacing": {
    "0": {
      "$type": "dimension",
      "$value": "0px"
    },
    "1": {
      "$type": "dimension",
      "$value": "4px"
    },
    "2": {
      "$type": "dimension",
      "$value": "8px"
    },
    "3": {
      "$type": "dimension",
      "$value": "12px"
    },
    "4": {
      "$type": "dimension",
      "$value": "16px"
    },
    "5": {
      "$type": "dimension",
      "$value": "20px"
    },
    "6": {
      "$type": "dimension",
      "$value": "24px"
    },
    "8": {
      "$type": "dimension",
      "$value": "32px"
    },
    "10": {
      "$type": "dimension",
      "$value": "40px"
    },
    "12": {
      "$type": "dimension",
      "$value": "48px"
    },
    "16": {
      "$type": "dimension",
      "$value": "64px"
    },
    "20": {
      "$type": "dimension",
      "$value": "80px"
    }
  },
  "typography": {
    "fontSize": {
      "xs": {
        "$type": "dimension",
        "$value": "12px"
      },
      "sm": {
        "$type": "dimension",
        "$value": "14px"
      },
      "base": {
        "$type": "dimension",
        "$value": "16px"
      },
      "lg": {
        "$type": "dimension",
        "$value": "18px"
      },
      "xl": {
        "$type": "dimension",
        "$value": "20px"
      },
      "2xl": {
        "$type": "dimension",
        "$value": "24px"
      },
      "3xl": {
        "$type": "dimension",
        "$value": "30px"
      },
      "4xl": {
        "$type": "dimension",
        "$value": "36px"
      },
      "5xl": {
        "$type": "dimension",
        "$value": "48px"
      }
    },
    "lineHeight": {
      "tight": {
        "$type": "number",
        "$value": 1.15
      },
      "snug": {
        "$type": "number",
        "$value": 1.3
      },
      "normal": {
        "$type": "number",
        "$value": 1.5
      },
      "relaxed": {
        "$type": "number",
        "$value": 1.7
      }
    },
    "fontWeight": {
      "regular": {
        "$type": "number",
        "$value": 400
      },
      "medium": {
        "$type": "number",
        "$value": 500
      },
      "semibold": {
        "$type": "number",
        "$value": 600
      },
      "bold": {
        "$type": "number",
        "$value": 700
      }
    }
  },
  "zIndex": {
    "base": {
      "$type": "number",
      "$value": 0
    },
    "sticky": {
      "$type": "number",
      "$value": 100
    },
    "overlay": {
      "$type": "number",
      "$value": 400
    },
    "modal": {
      "$type": "number",
      "$value": 500
    },
    "toast": {
      "$type": "number",
      "$value": 600
    }
  }
} as const;

export const foundationCssVariables = {
  "--dc-accessibility-focusRingWidth": "2px",
  "--dc-accessibility-focusRingOffset": "2px",
  "--dc-accessibility-minimumTarget": "44px",
  "--dc-accessibility-contrastBodyText": 4.5,
  "--dc-accessibility-contrastLargeText": 3,
  "--dc-breakpoint-sm": "640px",
  "--dc-breakpoint-md": "768px",
  "--dc-breakpoint-lg": "1024px",
  "--dc-breakpoint-xl": "1280px",
  "--dc-breakpoint-2xl": "1536px",
  "--dc-motion-duration-instant": "0ms",
  "--dc-motion-duration-fast": "150ms",
  "--dc-motion-duration-base": "240ms",
  "--dc-motion-duration-slow": "420ms",
  "--dc-motion-easing-standard": [
    0.2,
    0,
    0,
    1
  ],
  "--dc-motion-easing-emphasized": [
    0.2,
    0,
    0,
    1.2
  ],
  "--dc-radius-none": "0px",
  "--dc-radius-xs": "4px",
  "--dc-radius-sm": "6px",
  "--dc-radius-md": "8px",
  "--dc-radius-lg": "12px",
  "--dc-radius-xl": "16px",
  "--dc-radius-pill": "999px",
  "--dc-spacing-0": "0px",
  "--dc-spacing-1": "4px",
  "--dc-spacing-2": "8px",
  "--dc-spacing-3": "12px",
  "--dc-spacing-4": "16px",
  "--dc-spacing-5": "20px",
  "--dc-spacing-6": "24px",
  "--dc-spacing-8": "32px",
  "--dc-spacing-10": "40px",
  "--dc-spacing-12": "48px",
  "--dc-spacing-16": "64px",
  "--dc-spacing-20": "80px",
  "--dc-typography-fontSize-xs": "12px",
  "--dc-typography-fontSize-sm": "14px",
  "--dc-typography-fontSize-base": "16px",
  "--dc-typography-fontSize-lg": "18px",
  "--dc-typography-fontSize-xl": "20px",
  "--dc-typography-fontSize-2xl": "24px",
  "--dc-typography-fontSize-3xl": "30px",
  "--dc-typography-fontSize-4xl": "36px",
  "--dc-typography-fontSize-5xl": "48px",
  "--dc-typography-lineHeight-tight": 1.15,
  "--dc-typography-lineHeight-snug": 1.3,
  "--dc-typography-lineHeight-normal": 1.5,
  "--dc-typography-lineHeight-relaxed": 1.7,
  "--dc-typography-fontWeight-regular": 400,
  "--dc-typography-fontWeight-medium": 500,
  "--dc-typography-fontWeight-semibold": 600,
  "--dc-typography-fontWeight-bold": 700,
  "--dc-zIndex-base": 0,
  "--dc-zIndex-sticky": 100,
  "--dc-zIndex-overlay": 400,
  "--dc-zIndex-modal": 500,
  "--dc-zIndex-toast": 600
} as const;

export type FoundationTokens = typeof foundationTokens;
export type FoundationCssVariables = typeof foundationCssVariables;
