import type { DesignCThemeMode } from "./generated.js";

export type { DesignCThemeMode } from "./generated.js";

export const semanticColorKeys = [
  "background",
  "foreground",
  "surface",
  "surfaceAlt",
  "primary",
  "onPrimary",
  "accent",
  "onAccent",
  "cta",
  "onCta",
  "border",
  "muted",
  "mutedForeground",
  "success",
  "onSuccess",
  "warning",
  "onWarning",
  "danger",
  "onDanger",
  "focusRing"
] as const;

export const contrastPairs = [
  ["background", "foreground"],
  ["surface", "foreground"],
  ["surfaceAlt", "foreground"],
  ["primary", "onPrimary"],
  ["accent", "onAccent"],
  ["cta", "onCta"],
  ["muted", "mutedForeground"],
  ["success", "onSuccess"],
  ["warning", "onWarning"],
  ["danger", "onDanger"]
] as const;

export type SemanticColorKey = (typeof semanticColorKeys)[number];
export type SemanticColors = Record<SemanticColorKey, string>;

export interface LocalThemeToken {
  $type?: string;
  $value: string;
}

export interface LocalBrandPalette {
  id: string;
  name: string;
  mood: string[];
  density?: string;
  typography?: Record<string, string>;
  colors: Record<string, LocalThemeToken>;
}

export interface LocalSemanticTheme {
  mode: DesignCThemeMode;
  colors: Record<SemanticColorKey, LocalThemeToken>;
}

export interface LocalThemePack {
  id: string;
  name: string;
  mood: string[];
  density: string;
  typography: Record<string, string>;
  modes: Record<DesignCThemeMode, { colors: SemanticColors }>;
}

export function validateThemePack(theme: {
  name: string;
  brand: LocalBrandPalette;
  modes: Record<DesignCThemeMode, LocalSemanticTheme>;
}) {
  const { name, brand, modes } = theme;

  if (brand.id !== name) {
    throw new Error(`${name}: brand.id must match the theme id.`);
  }

  if (!brand.name || typeof brand.name !== "string") {
    throw new Error(`${name}: brand.name is required.`);
  }

  if (!Array.isArray(brand.mood) || brand.mood.length === 0) {
    throw new Error(`${name}: brand.mood must be a non-empty array.`);
  }

  for (const [colorName, colorToken] of Object.entries(brand.colors)) {
    assertHex(tokenValue(colorToken, `${name}: brand.colors.${colorName}`), `${name}: brand.colors.${colorName}`);
  }

  for (const modeName of ["light", "dark"] as const) {
    const mode = modes[modeName];
    if (mode.mode !== modeName) {
      throw new Error(`${name}: semantic.${modeName}.json mode must be "${modeName}".`);
    }

    for (const key of semanticColorKeys) {
      const value = tokenValue(mode.colors[key], `${name}.${modeName}.colors.${key}`);
      const resolved = resolveColor(value, brand.colors, `${name}.${modeName}.colors.${key}`);
      assertHex(resolved, `${name}.${modeName}.colors.${key}`);
    }
  }
}

export function resolveThemePack(theme: {
  name: string;
  brand: LocalBrandPalette;
  modes: Record<DesignCThemeMode, LocalSemanticTheme>;
}): LocalThemePack {
  return {
    id: theme.name,
    name: theme.brand.name,
    mood: theme.brand.mood,
    typography: theme.brand.typography ?? {},
    density: theme.brand.density ?? "balanced",
    modes: {
      light: {
        colors: resolveSemanticColors(theme.modes.light, theme.brand.colors, `${theme.name}.light`)
      },
      dark: {
        colors: resolveSemanticColors(theme.modes.dark, theme.brand.colors, `${theme.name}.dark`)
      }
    }
  };
}

export function renderThemeCss(themeId: string, resolved: LocalThemePack) {
  const blocks: string[] = ["/* Generated by designc-theme. Do not edit by hand. */"];

  for (const modeName of ["light", "dark"] as const) {
    const colors = resolved.modes[modeName].colors;
    const lines = semanticColorKeys.map((key) => `  --dc-color-${toKebab(key)}: ${colors[key]};`);
    blocks.push(`:root[data-dc-theme="${themeId}"][data-dc-mode="${modeName}"],\n[data-dc-theme="${themeId}"][data-dc-mode="${modeName}"] {\n${lines.join("\n")}\n}`);
  }

  return `${blocks.join("\n\n")}\n`;
}

export function checkThemeContrast(resolved: LocalThemePack) {
  const failures: string[] = [];

  for (const modeName of ["light", "dark"] as const) {
    const colors = resolved.modes[modeName].colors;
    for (const [backgroundKey, foregroundKey] of contrastPairs) {
      const ratio = contrastRatio(colors[foregroundKey], colors[backgroundKey]);
      if (ratio < 4.5) {
        failures.push(`${resolved.id}/${modeName} ${foregroundKey} on ${backgroundKey}: ${ratio.toFixed(2)} < 4.5`);
      }
    }
  }

  return failures;
}

function resolveSemanticColors(
  semantic: LocalSemanticTheme,
  brandColors: LocalBrandPalette["colors"],
  label: string
): SemanticColors {
  return Object.fromEntries(
    semanticColorKeys.map((key) => [
      key,
      resolveColor(tokenValue(semantic.colors[key], `${label}.${key}`), brandColors, `${label}.${key}`)
    ])
  ) as SemanticColors;
}

function assertHex(value: string, label: string) {
  if (!/^#[0-9a-fA-F]{6}$/.test(value)) {
    throw new Error(`${label} must be a #RRGGBB hex color.`);
  }
}

function tokenValue(token: LocalThemeToken | undefined, label: string) {
  if (!token || typeof token !== "object" || !("$value" in token)) {
    throw new Error(`${label} must be a DTCG token object with $value.`);
  }

  return token.$value;
}

function resolveColor(value: string, brandColors: LocalBrandPalette["colors"], label: string) {
  const refMatch = value.match(/^\{brand\.colors\.([a-zA-Z0-9_-]+)\}$/);
  if (refMatch) {
    const colorName = refMatch[1];
    const color = brandColors[colorName];
    if (!color) {
      throw new Error(`${label} references missing brand color "${colorName}".`);
    }

    return tokenValue(color, `brand.colors.${colorName}`);
  }

  return value;
}

function contrastRatio(foreground: string, background: string) {
  const fg = relativeLuminance(foreground);
  const bg = relativeLuminance(background);
  const lighter = Math.max(fg, bg);
  const darker = Math.min(fg, bg);
  return (lighter + 0.05) / (darker + 0.05);
}

function relativeLuminance(hex: string) {
  const rgb = hex
    .replace("#", "")
    .match(/.{2}/g)
    ?.map((part) => Number.parseInt(part, 16))
    .map(channelToLinear);

  if (!rgb || rgb.length !== 3) {
    throw new Error(`Invalid hex color: ${hex}`);
  }

  return 0.2126 * rgb[0] + 0.7152 * rgb[1] + 0.0722 * rgb[2];
}

function channelToLinear(channel: number) {
  const normalized = channel / 255;
  return normalized <= 0.03928
    ? normalized / 12.92
    : Math.pow((normalized + 0.055) / 1.055, 2.4);
}

function toKebab(value: string) {
  return value.replace(/[A-Z]/g, (match) => `-${match.toLowerCase()}`);
}
