// Generated by scripts/build-theme-packs.mjs. Do not edit by hand.
export const designcThemes = {
  "company-landing": {
    "id": "company-landing",
    "name": "Company Landing",
    "mood": [
      "credible",
      "sharp",
      "capable",
      "business-focused"
    ],
    "typography": {
      "display": "confident editorial sans",
      "body": "neutral business sans"
    },
    "density": "information-dense",
    "modes": {
      "light": {
        "colors": {
          "background": "#F7F8F5",
          "foreground": "#151713",
          "surface": "#FFFFFF",
          "surfaceAlt": "#ECEFE8",
          "primary": "#2F7D55",
          "onPrimary": "#FFFFFF",
          "accent": "#72521F",
          "onAccent": "#FFFFFF",
          "cta": "#151713",
          "onCta": "#FFFFFF",
          "border": "#DADDD6",
          "muted": "#E6E9E2",
          "mutedForeground": "#464D42",
          "success": "#2F7D55",
          "onSuccess": "#FFFFFF",
          "warning": "#72521F",
          "onWarning": "#FFFFFF",
          "danger": "#A64040",
          "onDanger": "#FFFFFF",
          "focusRing": "#2F7D55"
        }
      },
      "dark": {
        "colors": {
          "background": "#111411",
          "foreground": "#F7F8F5",
          "surface": "#1C211B",
          "surfaceAlt": "#252B24",
          "primary": "#8CCEA8",
          "onPrimary": "#0B2416",
          "accent": "#D7A45F",
          "onAccent": "#291904",
          "cta": "#F7F8F5",
          "onCta": "#111411",
          "border": "#384035",
          "muted": "#2B3329",
          "mutedForeground": "#D4DCCD",
          "success": "#8CCEA8",
          "onSuccess": "#0B2416",
          "warning": "#D7A45F",
          "onWarning": "#291904",
          "danger": "#F09A9A",
          "onDanger": "#351010",
          "focusRing": "#8CCEA8"
        }
      }
    }
  },
  "cosmetics": {
    "id": "cosmetics",
    "name": "Cosmetics Brand",
    "mood": [
      "clean",
      "sensory",
      "premium",
      "ingredient-led"
    ],
    "typography": {
      "display": "high-contrast serif",
      "body": "quiet grotesk sans"
    },
    "density": "editorial",
    "modes": {
      "light": {
        "colors": {
          "background": "#F8F3EC",
          "foreground": "#2B241F",
          "surface": "#FFFDF8",
          "surfaceAlt": "#EFE4D7",
          "primary": "#4F6F52",
          "onPrimary": "#FFFFFF",
          "accent": "#9A4A53",
          "onAccent": "#FFFFFF",
          "cta": "#2B241F",
          "onCta": "#FFFFFF",
          "border": "#DED2C4",
          "muted": "#E9DED2",
          "mutedForeground": "#4D4137",
          "success": "#2F7D55",
          "onSuccess": "#FFFFFF",
          "warning": "#735600",
          "onWarning": "#FFFFFF",
          "danger": "#A43B40",
          "onDanger": "#FFFFFF",
          "focusRing": "#4F6F52"
        }
      },
      "dark": {
        "colors": {
          "background": "#171411",
          "foreground": "#F8F3EC",
          "surface": "#211C18",
          "surfaceAlt": "#2D251F",
          "primary": "#A8C7A0",
          "onPrimary": "#152015",
          "accent": "#E1A9AF",
          "onAccent": "#2B1518",
          "cta": "#F8F3EC",
          "onCta": "#171411",
          "border": "#4A3D34",
          "muted": "#3A3029",
          "mutedForeground": "#D8C9BC",
          "success": "#95D8AE",
          "onSuccess": "#0D2416",
          "warning": "#E3C15A",
          "onWarning": "#2A2000",
          "danger": "#F0A0A3",
          "onDanger": "#381010",
          "focusRing": "#A8C7A0"
        }
      }
    }
  },
  "group-dating": {
    "id": "group-dating",
    "name": "Group Dating App",
    "mood": [
      "social",
      "warm",
      "safe",
      "energetic"
    ],
    "typography": {
      "display": "rounded expressive sans",
      "body": "friendly readable sans"
    },
    "density": "lively",
    "modes": {
      "light": {
        "colors": {
          "background": "#FFF7EC",
          "foreground": "#24201C",
          "surface": "#FFFFFF",
          "surfaceAlt": "#F7E4D2",
          "primary": "#C93138",
          "onPrimary": "#FFFFFF",
          "accent": "#087F6F",
          "onAccent": "#FFFFFF",
          "cta": "#C93138",
          "onCta": "#FFFFFF",
          "border": "#F1D9C5",
          "muted": "#F4E5D7",
          "mutedForeground": "#514238",
          "success": "#087F6F",
          "onSuccess": "#FFFFFF",
          "warning": "#735000",
          "onWarning": "#FFFFFF",
          "danger": "#C93138",
          "onDanger": "#FFFFFF",
          "focusRing": "#1F6F93"
        }
      },
      "dark": {
        "colors": {
          "background": "#171312",
          "foreground": "#FFF7EC",
          "surface": "#241B19",
          "surfaceAlt": "#30231F",
          "primary": "#FF7377",
          "onPrimary": "#2D0B0D",
          "accent": "#47D8BE",
          "onAccent": "#052B25",
          "cta": "#FF7377",
          "onCta": "#2D0B0D",
          "border": "#4B3630",
          "muted": "#3B2B26",
          "mutedForeground": "#EBCBB7",
          "success": "#47D8BE",
          "onSuccess": "#052B25",
          "warning": "#F2C85F",
          "onWarning": "#2B1B00",
          "danger": "#FF7377",
          "onDanger": "#2D0B0D",
          "focusRing": "#47D8BE"
        }
      }
    }
  },
  "muen": {
    "id": "muen",
    "name": "Muen AI Chatbot",
    "mood": [
      "intelligent",
      "calm",
      "companion-like",
      "slightly mysterious"
    ],
    "typography": {
      "display": "technical but soft sans",
      "body": "chat-optimized readable sans"
    },
    "density": "compact",
    "modes": {
      "light": {
        "colors": {
          "background": "#F1F7F5",
          "foreground": "#101316",
          "surface": "#FFFFFF",
          "surfaceAlt": "#DDEAE6",
          "primary": "#0B4A4A",
          "onPrimary": "#FFFFFF",
          "accent": "#4D6C00",
          "onAccent": "#FFFFFF",
          "cta": "#101316",
          "onCta": "#FFFFFF",
          "border": "#CBD9D5",
          "muted": "#E2ECE9",
          "mutedForeground": "#3B4848",
          "success": "#227A46",
          "onSuccess": "#FFFFFF",
          "warning": "#6A5A00",
          "onWarning": "#FFFFFF",
          "danger": "#A13D4B",
          "onDanger": "#FFFFFF",
          "focusRing": "#0B4A4A"
        }
      },
      "dark": {
        "colors": {
          "background": "#101316",
          "foreground": "#EEF4F2",
          "surface": "#1A2023",
          "surfaceAlt": "#252B2E",
          "primary": "#C7FF6B",
          "onPrimary": "#172100",
          "accent": "#8BE7FF",
          "onAccent": "#052B33",
          "cta": "#C7FF6B",
          "onCta": "#172100",
          "border": "#2E383B",
          "muted": "#20282B",
          "mutedForeground": "#CADAD6",
          "success": "#8ED9A8",
          "onSuccess": "#092314",
          "warning": "#E6D66A",
          "onWarning": "#272000",
          "danger": "#F19BA6",
          "onDanger": "#350D14",
          "focusRing": "#8BE7FF"
        }
      }
    }
  }
} as const;

export const themeNames = Object.keys(designcThemes) as Array<keyof typeof designcThemes>;

export type DesignCThemeRegistry = typeof designcThemes;
export type DesignCThemeName = keyof DesignCThemeRegistry;
export type DesignCThemeMode = "light" | "dark";
